name: "Linter"
description: "Prepare the super linter logs to be used later"
inputs:
  code_scan_out:
    description: 'code to scan'
    required: true
outputs:
  code_scan_output:
    description: 'super linter logs cleaning output'
    value: ${{ steps.cleaning_code.outputs.content }}
runs:
  using: "composite"
  steps:
    - id: cleaning_code
      shell: bash
      run: |
        codecontent="$(ls ./code_scan/*.tap | xargs cat)"
        codecontent="${codecontent//'%'/'%25'}"
        codecontent="${codecontent//$'\n'/'%0A'}"
        codecontent="${codecontent//$'\r'/'%0D'}"
        codecontent="${codecontent//$'$'/'\$'}"
        codecontent="${codecontent//$'`'/'%60'}"
        echo "::set-output name=content::$codecontent"