name: "Linter"
description: "The First Action"
inputs:
  code_scan_out:
    description: 'GITHUB_TOKEN'
    required: true
outputs:
  code_scan_output:
    description: 'tf plan output'
    value: ${{ steps.cleaning_code.outputs.content }}
runs:
  using: "composite"
  steps:
    - id: cleaning_code
      shell: bash
      run: |
        logcontent="$(ls ./code_scan/*.tap | xargs cat)"
        logcontent="${logcontent//'%'/'%25'}"
        logcontent="${logcontent//$'\n'/'%0A'}"
        logcontent="${logcontent//$'\r'/'%0D'}"
        logcontent="${logcontent//$'$'/'\$'}"
        logcontent="${logcontent//$'`'/'%60'}"
        echo "::set-output name=content::$logcontent"