name: 'CI Script'
description: 'CI Script'
inputs:
  terraform_version:
    description: 'Who to greet'
    required: false
    default: '0.13.5'
# outputs:
runs:
  using: "composite"
  steps:
    - run: cd ./terraform
      shell: bash
    - id: tf_init
      run: docker run -i hashicorp/terraform:${{ inputs.terraform_version }} init
      shell: bash
    - id: tf_plan
      run: docker run -i hashicorp/terraform:${{ inputs.terraform_version }} plan -no-color
      shell: bash